---
- hosts: servers
  vars:
    dotfiles:
      - file: "bash_login"
      - file: "bash_aliases"
      - file: "qux_python"
  vars_files:
    - userlist.yml
  tasks:
    - name: Copy dotfiles to ~root
      get_url:
        url: "https://raw.githubusercontent.com/vishalapte/foundation/main/shell/{{ item.file }}"
        dest: "$HOME/.{{ item.file }}"
        force: no
      with_items: "{{ dotfiles }}"

    - name: "Add user"
      user:
        name: "{{ item.login }}"
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_comment: "{{ item.login }}@{{ ansible_hostname }}"
        force: no
      with_items: "{{ users }}"
      when: users is defined

    - name: Copy dotfiles to ~{{ item[1].login }}
      get_url:
        url: "https://raw.githubusercontent.com/vishalapte/foundation/main/shell/{{ item[0].file }}"
        dest: "/home/{{ item[1].login }}/.{{ item[0].file }}"
        owner: "{{ item[1].login }}"
        group: "{{ item[1].login }}"
        mode: "0644"
        force: no
        # when: item[1].dotfiles is defined
      with_nested:
      - "{{ dotfiles }}"
      - "{{ users }}"
      when: dotfiles is defined and users is defined

    - name: Set authorized_key - https://github.com/githubid.keys
      authorized_key:
        user: "{{ item.login }}"
        state: present
        key: "https://github.com/{{ item.github }}.keys"
      with_items: "{{ users }}"
      when: users is defined and item.github is defined

    - name: Set authorized_key - custom
      authorized_key:
        user: "{{ item.login }}"
        state: present
        key: "{{ item.key }}"
      with_items: "{{ users }}"
      when: users is defined and item.key is defined

    - name: "Add user to sudoers"
      user:
        name: "{{ item.login }}"
        groups: sudo
        append: yes
      with_items: "{{ users }}"
      when: users is defined and item.sudo is defined
...
