---
- hosts: servers
  vars:
    users:
      - login: parag
      - login: jm_7c6e70d8
        authkey: https://github.com/jayanta-1e9.keys
      - login: pt_879b5697
  become: yes
  tasks:
    - name: Add vishal @ {{ ansible_hostname }} and generate ED25519 key
      user:
        name: vishal
        groups: sudo
        append: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_comment: vishal@{{ ansible_hostname }}
        force: no

    - name: Set authorized key from file
      authorized_key:
        user: vishal
        state: present
        key: "https://vishalapte.com/auth_keys"

    - name: "Add user"
      user:
        name: "{{ item.login }}"
        groups: sudo
        append: yes
        shell: /bin/bash
      with_items: "{{ users }}"

    - name: Set authorized_key
      authorized_key:
        user: "{{ item.login }}"
        state: present
        key: "{{ item.authkey }}"
      when: item.authkey is defined
      with_items: "{{ users }}"
...
