---
- hosts: servers
  vars:
    files:
      - file: "bash_login"
      - file: "bash_aliases"
      - file: "qux_python"
  # vars_files:
  #   - userlist.yml
  tasks:
    # Root
    - name: Copy login scripts to root
      get_url:
        url: "https://raw.githubusercontent.com/vishalapte/foundation/main/shell/{{ item.file }}"
        dest: "$HOME/.{{ item.file }}"
        force: no
      with_items: "{{ files }}"
    # Vishal
    - name: Add vishal and generate ed25519 key
      user:
        name: vishal
        groups: sudo
        append: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_comment: vishal@{{ ansible_hostname }}
        force: no
    - name: Set authorized key from file
      authorized_key:
        user: vishal
        state: present
        key: "https://vishalapte.com/auth_keys"
        # key: "{{ lookup('file', '/Users/vishal/dotssh/id_rsa.pub') }}"
    - name: Copy login scripts to vishal
      get_url:
        url: "https://raw.githubusercontent.com/vishalapte/foundation/main/shell/{{ item.file }}"
        dest: "/home/vishal/.{{ item.file }}"
        owner: vishal
        group: vishal
        mode: "0644"
        force: no
      with_items: "{{ files }}"
    # Other users
    - name: "Add user"
      user:
        name: "{{ item.login }}"
        groups: sudo
        append: yes
        shell: /bin/bash
      when: users is defined
      with_items: "{{ users }}"
    - name: Set authorized_key
      authorized_key:
        user: "{{ item.login }}"
        state: present
        key: "{{ item.authkey }}"
      when: users is defined and item.authkey is defined
      with_items: "{{ users }}"
...
